version: "3"
services:
  # start the ganache cli container
  ganache-cli:
    container_name: ganache-cli
    build:
      context: ./docker/ganache
    # note host:container
    ports:
      - 8545:8545
  truffle_suite:
    container_name: truffle_suite
    build:
      context:
        ./docker/truffle
        # volumes
    volumes:
      - ".:/workspace"
    # command: >
    #     bash
    stdin_open: true # docker run -i
    tty: true # docker run -t
